# Generated by Django 4.2 on 2023-04-13 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="dat_of_birth",
            new_name="date_of_birth",
        ),
    ]
